AWSTemplateFormatVersion: 2010-09-09

Parameters:

  ElasticSearchCidrIp:
    Description: CIDR block from which elasticsearch will allow traffic
    Type: String

Resources:

  LoggingStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Name: !Sub "${AWS::StackName}-logging"
        ElasticSearchCidrIp: !Ref ElasticSearchCidrIp
      TemplateURL: logging/cloudformation.yaml
