AWSTemplateFormatVersion: 2010-09-09

Parameters:

  Name:
    Type: String

  LogBucket:
    Type: String

Outputs:

  PrivateBucket:
    Value: !Ref PrivateBucket

  PublicBucket:
    Value: !Ref PublicBucket

  BrowseUrl:
    Value: !Sub "https://${PublicBucket.DomainName}/"

Resources:

  PrivateBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${Name}-private"
      LoggingConfiguration:
        DestinationBucketName: !Ref LogBucket
        LogFilePrefix: private/

  PublicBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${Name}-public"
      LoggingConfiguration:
        DestinationBucketName: !Ref LogBucket
        LogFilePrefix: public/

  PublicBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref PublicBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal: "*"
          Action: s3:GetObject
          Resource: !Sub "arn:aws:s3:::${PublicBucket}/*"
